"""add VehicleLocation

Revision ID: 23c5d550a4a5
Revises: d166ecfdae66
Create Date: 2025-06-26 20:49:07.733696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c5d550a4a5'
down_revision = 'd166ecfdae66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('speed_mph', sa.Float(), nullable=True),
    sa.Column('is_ecu_speed', sa.Boolean(), nullable=True),
    sa.Column('formatted_location', sa.String(), nullable=True),
    sa.Column('address_id', sa.String(), nullable=True),
    sa.Column('address_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_locations_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_locations_vehicle_id'))

    op.drop_table('vehicle_locations')
    # ### end Alembic commands ###
