"""Add driver and driver_vehicle_assignments tables

Revision ID: 9f0c6d56f300
Revises: 23c5d550a4a5
Create Date: 2025-12-11 10:14:06.091187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0c6d56f300'
down_revision = '23c5d550a4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_vehicle_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('assignment_start', sa.DateTime(), nullable=False),
    sa.Column('assignment_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_vehicle_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_vehicle_assignments_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_vehicle_assignments_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_vehicle_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_vehicle_assignments_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_driver_vehicle_assignments_driver_id'))

    op.drop_table('driver_vehicle_assignments')
    op.drop_table('drivers')
    # ### end Alembic commands ###
