"""Initial migration

Revision ID: d166ecfdae66
Revises: 
Create Date: 2025-06-23 23:22:36.927323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd166ecfdae66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('maintenance_id', sa.String(), nullable=True),
    sa.Column('gateway_model', sa.String(), nullable=True),
    sa.Column('gateway_serial', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geofence_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('address_name', sa.String(), nullable=True),
    sa.Column('address_formatted', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geofence_events')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
