"""add composite indices

Revision ID: 648b513fafc7
Revises: 4f42c8d834fa
Create Date: 2025-12-25 12:55:12.028445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648b513fafc7'
down_revision: Union[str, None] = '4f42c8d834fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_geofence_events_vehicle_time', 'geofence_events', ['vehicle_id', 'event_time'], unique=False)
    op.drop_index(op.f('ix_vehicle_locations_vehicle_id'), table_name='vehicle_locations')
    op.create_index('ix_vehicle_locations_vehicle_timestamp', 'vehicle_locations', ['vehicle_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_locations_vehicle_timestamp', table_name='vehicle_locations')
    op.create_index(op.f('ix_vehicle_locations_vehicle_id'), 'vehicle_locations', ['vehicle_id'], unique=False)
    op.drop_index('ix_geofence_events_vehicle_time', table_name='geofence_events')
    # ### end Alembic commands ###
