"""generate tables for schedules and routes

Revision ID: aba8cad5405a
Revises: 
Create Date: 2026-03-24 09:59:01.112660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba8cad5405a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('route_color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('maintenance_id', sa.String(), nullable=True),
    sa.Column('gateway_model', sa.String(), nullable=True),
    sa.Column('gateway_serial', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_schedules_to_day_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_schedule_id', sa.Integer(), nullable=False),
    sa.Column('day_schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bus_schedule_id'], ['bus_schedules.id'], ),
    sa.ForeignKeyConstraint(['day_schedule_id'], ['day_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('bus_schedule_id', 'bus_schedules_to_day_schedules', ['day_schedule_id'], unique=False)
    op.create_table('date_to_day_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_schedule_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['day_schedule_id'], ['day_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_date_to_day_schedules_day_schedule_id', 'date_to_day_schedules', ['day_schedule_id'], unique=False)
    op.create_table('driver_vehicle_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('assignment_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assignment_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_vehicle_assignments_driver_id'), 'driver_vehicle_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_vehicle_assignments_vehicle_id'), 'driver_vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_table('etas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('etas', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_etas_vehicle_timestamp', 'etas', ['vehicle_id', 'timestamp'], unique=False)
    op.create_table('geofence_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('address_name', sa.String(), nullable=True),
    sa.Column('address_formatted', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_geofence_events_vehicle_time', 'geofence_events', ['vehicle_id', 'event_time'], unique=False)
    op.create_table('predicted_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predicted_locations_vehicle_timestamp', 'predicted_locations', ['vehicle_id', 'timestamp'], unique=False)
    op.create_table('route_to_bus_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('bus_schedule_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.TIME(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bus_schedule_id'], ['bus_schedules.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bus_schedule_id', 'time', name='uq_route_to_bus_schedules_bus_schedule_id_time')
    )
    op.create_index('route_id', 'route_to_bus_schedules', ['time'], unique=False)
    op.create_table('stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stops_route_id', 'stops', ['route_id'], unique=False)
    op.create_table('vehicle_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('speed_mph', sa.Float(), nullable=True),
    sa.Column('is_ecu_speed', sa.Boolean(), nullable=False),
    sa.Column('formatted_location', sa.String(), nullable=True),
    sa.Column('address_id', sa.String(), nullable=True),
    sa.Column('address_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'timestamp', name='uq_vehicle_locations_vehicle_timestamp')
    )
    op.create_index('ix_vehicle_locations_vehicle_timestamp', 'vehicle_locations', ['vehicle_id', 'timestamp'], unique=False)
    op.create_table('polylines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departure_stop_id', sa.Integer(), nullable=False),
    sa.Column('arrival_stop_id', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['arrival_stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['departure_stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arrival_stop_id', 'departure_stop_id', name='uq_polylines_arrival_departure_stops')
    )
    op.create_index('arrival_stop_id', 'polylines', ['departure_stop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('arrival_stop_id', table_name='polylines')
    op.drop_table('polylines')
    op.drop_index('ix_vehicle_locations_vehicle_timestamp', table_name='vehicle_locations')
    op.drop_table('vehicle_locations')
    op.drop_index('ix_stops_route_id', table_name='stops')
    op.drop_table('stops')
    op.drop_index('route_id', table_name='route_to_bus_schedules')
    op.drop_table('route_to_bus_schedules')
    op.drop_index('ix_predicted_locations_vehicle_timestamp', table_name='predicted_locations')
    op.drop_table('predicted_locations')
    op.drop_index('ix_geofence_events_vehicle_time', table_name='geofence_events')
    op.drop_table('geofence_events')
    op.drop_index('ix_etas_vehicle_timestamp', table_name='etas')
    op.drop_table('etas')
    op.drop_index(op.f('ix_driver_vehicle_assignments_vehicle_id'), table_name='driver_vehicle_assignments')
    op.drop_index(op.f('ix_driver_vehicle_assignments_driver_id'), table_name='driver_vehicle_assignments')
    op.drop_table('driver_vehicle_assignments')
    op.drop_index('ix_date_to_day_schedules_day_schedule_id', table_name='date_to_day_schedules')
    op.drop_table('date_to_day_schedules')
    op.drop_index('bus_schedule_id', table_name='bus_schedules_to_day_schedules')
    op.drop_table('bus_schedules_to_day_schedules')
    op.drop_table('vehicles')
    op.drop_table('routes')
    op.drop_table('drivers')
    op.drop_table('day_schedules')
    op.drop_table('bus_schedules')
    # ### end Alembic commands ###
