"""enforce uniqueness constraint of vehicle and timestamp

Revision ID: ac296168d213
Revises: 648b513fafc7
Create Date: 2025-12-25 16:06:42.170853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac296168d213'
down_revision: Union[str, None] = '648b513fafc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vehicle_locations_vehicle_timestamp', 'vehicle_locations', ['vehicle_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vehicle_locations_vehicle_timestamp', 'vehicle_locations', type_='unique')
    # ### end Alembic commands ###
