# .github/workflows/deploy-to-dokku.yml
name: Deploy to Dokku

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      dokku_host:
        required: true
      dokku_app:
        required: true
      ssh_key:
        required: true

jobs:
  deploy:
    runs-on: [self-hosted]

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ssh_key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.dokku_host }} >> ~/.ssh/known_hosts

      - name: Deploy to Dokku
        run: |
          git remote remove dokku
          git remote add dokku dokku@${{ secrets.dokku_host }}:${{ secrets.dokku_app }}
          git push dokku HEAD:main -f
