name: Deploy to Dokku

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      dokku_host:
        required: true
      dokku_app:
        required: true
      ssh_key:
        required: true

jobs:
  deploy:
    runs-on: [self-hosted]

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_type == 'tag' && 'main' || github.ref_name }}
          fetch-depth: 0

      - name: Set up SSH
        run: |
          echo "${{ secrets.ssh_key }}" > temp_key
          chmod 600 temp_key

      - name: Deploy to Dokku
        run: |
          git remote remove dokku 2>/dev/null || true
          git remote add dokku dokku@${{ secrets.dokku_host }}:${{ secrets.dokku_app }}
          if [ "${{ inputs.environment }}" = "production" ]; then
            GIT_SSH_COMMAND="ssh -i temp_key -o StrictHostKeyChecking=no" git push dokku HEAD:production
          else
            GIT_SSH_COMMAND="ssh -i temp_key -o StrictHostKeyChecking=no" git push dokku HEAD:production -f
          fi
