# .github/workflows/deploy-to-dokku.yml
name: Deploy to Dokku

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      dokku_host:
        required: true
      dokku_app:
        required: true
      ssh_key:
        required: true

jobs:
  deploy:
    runs-on: [self-hosted]

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Set up SSH
        run: |
          echo "${{ secrets.ssh_key }}" > temp_key
          chmod 600 temp_key

      - name: Deploy to Dokku
        run: |
          git remote remove dokku
          git remote add dokku dokku@${{ secrets.dokku_host }}:${{ secrets.dokku_app }}
          GIT_SSH_COMMAND="ssh -i temp_key -o StrictHostKeyChecking=no" git push dokku HEAD:main -f
