name: Deploy to Staging domains

on:
  workflow_dispatch:

jobs:
  staging-web-shuttles:
    name: Deploy to staging-web-shuttles.rpi.edu
    uses: ./.github/workflows/deploy-to-dokku.yml
    with:
      environment: staging
    secrets:
      dokku_host: ${{ secrets.DOKKU_HOST_STAGING }}
      dokku_app: ${{ secrets.DOKKU_APP_STAGING_1 }}
      ssh_key: ${{ secrets.DOKKU_SSH_KEY_STAGING }}
  staging-api-shuttles:
    name: Deploy to staging-api.shuttles.rpi.edu
    uses: ./.github/workflows/deploy-to-dokku.yml
    with:
      environment: staging
    secrets:
      dokku_host: ${{ secrets.DOKKU_HOST_STAGING }}
      dokku_app: ${{ secrets.DOKKU_APP_STAGING_2 }}
      ssh_key: ${{ secrets.DOKKU_SSH_KEY_STAGING }}
  web-shuttletracker-app:
    name: Deploy to web.shuttletracker.app
    uses: ./.github/workflows/deploy-to-dokku.yml
    with:
      environment: staging
    secrets:
      dokku_host: ${{ secrets.DOKKU_HOST_STAGING }}
      dokku_app: ${{ secrets.DOKKU_APP_STAGING_3 }}
      ssh_key: ${{ secrets.DOKKU_SSH_KEY_STAGING }}
  web-shuttles:
    name: Deploy to web-shuttles.rpi.edu
    uses: ./.github/workflows/deploy-to-dokku.yml
    with:
      environment: staging
    secrets:
      dokku_host: ${{ secrets.DOKKU_HOST_STAGING }}
      dokku_app: ${{ secrets.DOKKU_APP_STAGING_4 }}
      ssh_key: ${{ secrets.DOKKU_SSH_KEY_STAGING }}
