name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-to-dokku.yml
    with:
      environment: staging
    secrets:
      dokku_host: ${{ secrets.DOKKU_HOST_STAGING }}
      dokku_app: ${{ secrets.DOKKU_APP_STAGING }}
      ssh_key: ${{ secrets.DOKKU_SSH_KEY_STAGING }}
